app = "gamestore"  # Remplacez par le nom de votre application

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"  # Port sur lequel votre application PHP écoute (modifiez-le si nécessaire)

[[services]]
  internal_port = 8080  # Port interne de l'application PHP (modifiez-le si nécessaire)
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0






